#!/usr/bin/perl
# Run me from cron as
#  perl -I/path/to/kirin pdns-secondarydns "DBI:mysql:database=pdns;host=192.168..." pdns $assword

use strict;
use warnings;

my ($dsn, $user, $password) = @ARGV
    or die "You need to supply DSN, username and password";
    # It's cron, so errors will be emailed back to root - no need to send

do 'kirin.pl';

my $dbh = DBI->connect($dsn, $user, $password)
    || die "Cannot connect to database Error: $!";

Kirin->cronjobhelper("secondary_dns", "Execute"); 

package Execute;

sub add_backup {
    my ($user, $domain, $primary) = @_;
    $domain = Kirin::DB::Domain->retrieve($domain);
    if (!$domain) { return } # Domain has disappeared, no longer hosting
    $dbh->do("insert into domains (name, master, type, account) 
            values (?,?,?,?)", undef, 
        $domain->domainname, $primary, "SLAVE", $user->username)
        or die "Could not insert domain ".$dbh->errstr;
}

sub remove_backup {
    my ($user, $domain, $primary) = @_;
    $domain = Kirin::DB::Domain->retrieve($domain);
    if (!$domain) { return } # Domain has disappeared, no longer hosting
    $dbh->do("delete from domains where name = ? and account = ?",
        undef, $domain->domainname, $user->username)
        or die "Could not delete domain ".$dbh->errstr;
}
